name = "student-support-api"
main = "src/index.ts"
compatibility_date = "2026-03-18"
compatibility_flags = [ "nodejs_compat" ]
minify = true

[[d1_databases]]
binding = "DB"
database_name = "student-wellness-db"
database_id = "5f6240a7-dcdc-469e-8583-9f4acac5c6ff"
